name: SY
favicon: null
layout_spectrum: 0
typography_spectrum: 0.19874104228802025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcfc'
    - '#211311'
    - '#bccbc7'
    - '#941d1c'
    - '#8c948a'
  brandStrength: 0.6875
  lightness: 0.5200728240888566
  saturation: 0.2921894753817469
  rhythmicContrast: 0.06413930538110435
purpose: []
